language: go

before_script:
  - go get github.com/miekg/dns
  - go get golang.org/x/crypto/ssh
  - go install auth
  - go install config
  - go install resolvertests

script:
  - go test -v -race ./...

notifications:
  email:
    on_success: never
    on_failure: never #always/change/never
